### ISSUE TITLE
nullptr not declared in codeblocks compilation

### ISSUE THREAD

**Issue by jgrun** [ArlinTawzer/CSCI2270_FinalProjectSortingAlgorithms#3]
I changed all of the to NULL instead and initialized it in the constructor rather than the header file because it didn't compile. You may want to change that.

**Comment by Cooper4President** [comment]
The 'nullptr' syntax was added with C++11. If you enable c++11 in the compiler flags that should eliminate the error. The readme file for this project says you must compile with c++11 enabled.
